---
title: "data_visualization"
author: "Cindy & Evelyn & Sophia"
format: html
editor: visual
---

```{r}
library(readr)
library(tidyverse)
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(dplyr)
library(tidyr)
library(fuzzyjoin)
library(lubridate)
library(ggplot2)
library(ggridges)
library(patchwork)
```

```{r}
data <- read_csv("https://raw.githubusercontent.com/CindySun0309/SDS300-Final-Project/main/data_cleaned_new.csv") 
data <- data |>
  filter(CRW_BAA != "NA")
data$longitude <- as.numeric(data$longitude)
data$latitude <- as.numeric(data$latitude)
```

```{r}
ggplot(data, aes(x =CRW_BAA, fill =CRW_BAA)) +
  geom_bar() +
  labs(title = "Distribution of outcome Variable",
       x = "CRW_BAA",
       y = "Count") +
  theme_classic() +
  theme(legend.position = "none")
```

```{r}
bleach_1 <- data |>
  filter(CRW_BAA == "1")
bleach_2 <- data |>
  filter(CRW_BAA == "2")
bleach_3 <- data |>
  filter(CRW_BAA == "3")
bleach_4 <- data |>
  filter(CRW_BAA == "4")
lat_range<- range(data$latitude)
long_range<- range(data$longitude)
lat_range
long_range
```

We wanted to know where are those bleached corals located, and how far it's from shore? Here are maps

```{r}

# Load world coastline data
world_coastline <- ne_coastline(scale = "medium", returnclass = "sf")

# Create a bounding box for the specified latitude and longitude ranges
bbox <- st_bbox(c(xmin = -77.5, xmax = -61.5, ymin = 12.5, ymax = 21.5), crs = st_crs(world_coastline))

# Filter coastline data within the bounding box
coastal_areas <- st_intersection(world_coastline, st_as_sfc(bbox))

# Plot the coastline
#plot(coastal_areas, col = "blue", main = "Coastal Areas", axes = TRUE)

plot_bleach1 <- ggplot() +
  geom_sf(data = coastal_areas, color = "blue") +
  geom_point(data = bleach_1, aes(x = longitude, y = latitude), color = "green", size = 3)+
  labs(title = "Coastal Areas with Marked Locations", x = "Longitude", y = "Latitude") +
  theme_minimal()
plot_bleach1
```

```{r}
plot_bleach2 <- ggplot() +
  geom_sf(data = coastal_areas, color = "blue") +
  geom_point(data = bleach_2, aes(x = longitude, y = latitude), color = "pink", size = 3)+
  labs(title = "Coastal Areas with Marked Locations", x = "Longitude", y = "Latitude") +
  theme_minimal()
plot_bleach2
```

```{r}
plot_bleach3 <- ggplot() +
  geom_sf(data = coastal_areas, color = "blue") +
  geom_point(data = bleach_3, aes(x = longitude, y = latitude), color = "orange", size = 3)+
  labs(title = "Coastal Areas with Marked Locations", x = "Longitude", y = "Latitude") +
  theme_minimal()
plot_bleach3
```

```{r}
plot_bleach4 <- ggplot() +
  geom_sf(data = coastal_areas, color = "blue") +
  geom_point(data = bleach_4, aes(x = longitude, y = latitude), color = "red", size = 3)+
  labs(title = "Coastal Areas with Marked Locations", x = "Longitude", y = "Latitude") +
  theme_minimal()
plot_bleach4
```

```{r}
clean_data <- read_csv("https://raw.githubusercontent.com/CindySun0309/SDS300-Final-Project/main/data_cleaned_new.csv")
head(clean_data)
```

```{r}
#prelim scatter
scatter <- ggplot(clean_data, aes(x = country, y = total)) +
  geom_point()+
  labs(title ="Scatterplot of Hard Coral Total Number by Country",
       x = "Country", 
       y = "Hard Coral Number")+
  coord_flip()+
  theme_classic()+ 
  theme(plot.title = element_text(size=10),
        plot.margin = margin(t = 2, r = 2, b = 2, l = 2, unit = "mm"))

scatter
```

```{r}
#histo
histo <- ggplot(clean_data, aes(x = total, y = country, fill = country)) +
  geom_density_ridges()+
  theme_classic()+
  labs(title = "Historgram of Hard Coral Number by Country",
       x = "Hard Coral Number", 
       y = "Country")+ 
  theme(plot.title = element_text(size=9),
        plot.margin = margin(t = 2, r = 2, b = 2, l = 2, unit = "mm"))
histo
```

```{r}
combined_plot <- scatter / histo 
combined_plot


```

```{r}
clean_data$CRW_SSTANOMALY<-scale(clean_data$CRW_SSTANOMALY, center=TRUE, scale=TRUE)[,1]

#prelim scatter
scatter2 <- ggplot(clean_data, aes(x = country, y = CRW_SSTANOMALY)) +
  geom_point()+
  labs(title ="Scatterplot of CRW_SSTANOMALY by Country",
       x = "Country", 
       y = "CRW_SSTANOMALY")+
  coord_flip()+
  theme_classic()+ 
  theme(plot.title = element_text(size=10),
        plot.margin = margin(t = 2, r = 2, b = 2, l = 2, unit = "mm"))

scatter2
```

```{r}
#histo
histo2 <- ggplot(clean_data, aes(x = CRW_SSTANOMALY, y = country, fill = country)) +
  geom_density_ridges()+
  theme_classic()+
  labs(title = "Historgram of CRW_SSTANOMALY by Country",
       x = "CRW_SSTANOMALY", 
       y = "Country")+ 
  theme(plot.title = element_text(size=7.5),
        plot.margin = margin(t = 5, r = 5, b = 5, l = 5, unit = "mm")) 
histo2
```

```{r}

combined_plot2 <- scatter2 / histo2
combined_plot2

```
